[project]
name = "debugging-q4"
version = "0.1.0"
description = "CCHC Assessment Debugging Q4"
authors = [{ name = "Carter Setlock", email = cset@gmail.com" }]
readme = "README.md"
requires-python = "<=3.11"
dependencies = [
    "dash",
    "numpy",
    "pandas"
]
